package guru.interlis.mabillon.security;

public enum Permission {
    VIEW_MABILLON,
    EDIT_GESCHAEFT,
    EDIT_DOSSIER,
    EDIT_UNTERLAGE,
    EDIT_AUFGABE,
    MANAGE_CATALOGS,
    MANAGE_MASTERDATA,
    MANAGE_REGISTRATURPLAN,
    MANAGE_INTERLIS_EXCHANGE,
    CLOSE_DOSSIER,
    RUN_DATA_QUALITY,
    MANAGE_ARCHIVE_DELIVERY
}
